version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: proxy
    main: ./cmd/proxy/main.go        # <-- your entrypoint
    binary: proxy                    # output name
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: archive
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    builds:
      - proxy

dockers:
  - id: proxy_linux_amd64
    image_templates:
      - "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:latest"
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx

  - id: proxy_linux_arm64
    image_templates:
      - "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:{{ .Tag }}-arm64"
      - "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:latest-arm64"
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx

# Optional: build multi-arch manifest
docker_manifests:
  - name_template: "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:{{ .Tag }}"
    image_templates:
      - "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:{{ .Tag }}-arm64"

  - name_template: "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:latest"
      - "ghcr.io/{{ .RepoOwner }}/{{ .ProjectName }}:latest-arm64"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: |-
    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

