version: "3"

vars:
  BINARY_NAME: "socks-server"
  DOCKER_IMAGE: "Pupumch/socks5"

tasks:

  new-tag:
    desc: "Generate a new semantic version tag and push it"
    cmds:
      - |
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
        echo "Last tag: $LAST_TAG"
        NEW_TAG=$(semver -i patch "$LAST_TAG")
        echo "New tag: v$NEW_TAG"
        git tag "v$NEW_TAG"
        git push origin "v$NEW_TAG"

  release-artifacts:
    desc: ""
    cmds:
      - goreleaser release --clean

  release:
    desc: "Full release: tag → build binaries → build docker → upload"
    cmds:
      - task: new-tag
      - task: release-artifacts
    silent: true
